HyCo supports https://github.com/onnx/onnx/blob/main/docs/Operators.md#Cast[onnx opset 13], https://pytorch.org/docs/stable/generated/torch.Tensor.to.html[torch.Tensor.to], {url_pt}torch.Tensor.int.html[torch.Tensor.int].

==== Attribute

[width="100%", cols="^.^20%h,^.^15%,^.^15%,.^50%", options="header"]
|===
|*Attribute* |*DataType* |*Support* |*Note*

|to |uint8 | 1 (INT8), +
 2 (UINT8), +
 3 (UINT16), +
 10 (float) |Defines the data type to which the elements of the input tensor are cast. Strictly must be one of the types from rcardkl_type_id_t enum.
|===

==== Restriction and Limitation

* CNNIP
** CNNIP does not support the `Cast` operator.

* DSP
** Supported input tensor dimension: [0, 7]
** Supported output tensor dimension: [0, 7]
** If the following condition(s) are not satisfied, then fallback to the reference implementation.
*** Both inputs and outputs are dense.
*** The number of input elements is greater or equal 256.
* If inputs or outputs are non-dense, then fallback to the reference implementation.
** If the input is inf/nan, the float32 to int8/int16 conversion is not supported.
** Supported the following conversion
|===
|*input* |*to*   |*output*
| bool   | float | int8
| int8   | uint8 | uint8
| uint8  | int8  | int8
| int8   | float | float
| float  | int8  | int8
| int16  | float | float
| float  | int16 | int16
|===
** In `torch.Tensor.to`, FP32 is not yet supported.
** `torch.Tensor.int` is not yet supported.