= LEGAL INFORMATION

Your access to and use of this material, along with any documents, software, specifications, reference board files, drawings, diagnostics and other information contained herein (collectively this "Material"), is subject to your (including the corporation or other legal entity you represent, collectively "You" or "Your") acceptance of the terms and conditions ("Terms of Use") set forth below. If You do not agree to these Terms of Use, you may not use this Material and shall immediately destroy any copy thereof.

== 1) Legal Notice.

This Material is being made available to You solely for Your internal use with those products and service offerings of Renesas Electronics Corporation ("Renesas"), its affiliates and/or licensors described in this Material, and shall not be used for any other purposes. This Material may not be altered, edited, or modified in any way without Renesas' prior written approval. You may not remove or alter any copyright, trademark, or other proprietary notices, legends, symbols, or labels appearing on or in This Material. Unauthorized use or disclosure of this Material or the information contained herein is strictly prohibited, and You agree to indemnify Renesas Technologies, its affiliates and licensors for any damages or losses suffered by Renesas, its affiliates and/or licensors for any such unauthorized uses or disclosures of this Material, in whole or part.

Renesas, its affiliates and/or licensors retain all rights and ownership in and to this Material and any derivative works thereof, including all intellectual property rights thereto. No license to any trademark, patent, copyright, mask work protection right or any other intellectual property right is either granted or implied by this Material or any information disclosed herein, including, but not limited to, any license to make, use, import or sell any product, service or technology offering embodying any of the information in this Material.

THIS MATERIAL IS BEING PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, WHETHER EXPRESSED, IMPLIED, STATUTORY OR OTHERWISE. TO THE MAXIMUM EXTENT PERMITTED BY LAW, RENESAS, ITS AFFILIATES AND/OR LICENSORS SPECIFICALLY DISCLAIM ALL WARRANTIES OF TITLE, MERCHANTABILITY, NON-INFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, SATISFACTORY QUALITY, COMPLETENESS OR ACCURACY, AND ALL WARRANTIES ARISING OUT OF TRADE USAGE OR OUT OF A COURSE OF DEALING OR COURSE OF PERFORMANCE. MOREOVER, NEITHER RENESAS, NOR ANY OF ITS AFFILIATES AND/OR LICENSORS, SHALL BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY EXPENSES, LOSSES, USE, OR ACTIONS HOWSOEVER INCURRED OR UNDERTAKEN BY YOU IN RELIANCE ON THIS MATERIAL.

Certain product kits, tools and other items referenced in this Material may require You to accept additional terms and conditions before accessing or using those items.

Technical data specified in this Material may be subject to U.S. and other applicable export control laws. Transmission contrary to U.S. and any other applicable law is strictly prohibited.

Nothing in this Material is an offer to sell any of the components or devices referenced herein.

This Material is subject to change without further notification.

In the event of a conflict between these Terms of Use and any other agreement (written or click-through, including, without limitation any non-disclosure agreement) executed by You and Renesas or a Renesas’ affiliate and/or licensor with respect to Your access to and use of this Material, the other agreement will control.

You can find more information regarding this Material on https://www.renesas.com/en/software-tool/hybrid-compiler-hyco#overview[Hybrid Compiler (HyCo) | Renesas]

These Terms of Use shall be governed by and construed and enforced in accordance with the laws of Japan, without regard to conflict of laws principles. All disputes arising out of these Terms of Use, shall be subject to the exclusive jurisdiction of the Tokyo District Courts, and each You hereby irrevocably submits to the exclusive jurisdiction of such courts for purposes of such proceedings.

== 2) Trademark and Product Attribution Statements.

Renesas is a trademark or registered trademark of Renesas Electronics Corporation. Other products and brand names referenced in this Material may be trademarks or registered trademarks of their respective owners.